name: FIXMYGLASS
favicon: null
layout_spectrum: 0.10696350340731442
typography_spectrum: 0.4923647134564817
title: AnyGlass AnyVehicle AnyWhere
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#141517'
    - '#fefefe'
    - '#6e6f71'
    - '#b1b2b3'
    - '#d43329'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
