name: FIXMYGLASS
favicon: null
layout_spectrum: 0.10696350340731442
typography_spectrum: 0.4923647134564817
title: AnyGlass AnyVehicle AnyWhere
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.19632525695487857
  lightness: 0.777485434897244
  saturation: 0.03786366758868098
  rhythmicContrast: 0.7766194844152778
purpose: []
